services:
  web:
    build: ./wedding_invitation
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wedding_invitation/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env_db.dev

volumes:
  postgres_data_dev:
