services:
  web:
    build:
      context: ./wedding_invitation
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
      - media_volume_prod:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - reverse-proxy
  db:
    image: postgres:17
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env_db.prod
    networks:
      - reverse-proxy
  nginx:
    build: ./nginx
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
      - media_volume_prod:/home/app/web/mediafiles
    expose:
      - 80
    depends_on:
      - web
    networks:
      - reverse-proxy

volumes:
  postgres_data_prod:
  static_volume_prod:
  media_volume_prod:

networks:
  reverse-proxy:
    external: true
